// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmjTU4aN86_emS-_F__jwCGOmN6HzWWKQ',
    appId: '1:337452625695:web:68e176bec2ed07f9da4a2a',
    messagingSenderId: '337452625695',
    projectId: 'chatter-ai-64d77',
    authDomain: 'chatter-ai-64d77.firebaseapp.com',
    storageBucket: 'chatter-ai-64d77.firebasestorage.app',
    measurementId: 'G-KPQ2210YZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkabRTh6Op2bzmE1gfiC-CEckC8Tq4bzk',
    appId: '1:337452625695:android:f13f4b4f2f30c1aeda4a2a',
    messagingSenderId: '337452625695',
    projectId: 'chatter-ai-64d77',
    storageBucket: 'chatter-ai-64d77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSZXXn6GC560uugTz6jvkPDgWB3gAAHs',
    appId: '1:337452625695:ios:6bb2757f88e4a9d0da4a2a',
    messagingSenderId: '337452625695',
    projectId: 'chatter-ai-64d77',
    storageBucket: 'chatter-ai-64d77.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKSZXXn6GC560uugTz6jvkPDgWB3gAAHs',
    appId: '1:337452625695:ios:6bb2757f88e4a9d0da4a2a',
    messagingSenderId: '337452625695',
    projectId: 'chatter-ai-64d77',
    storageBucket: 'chatter-ai-64d77.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmjTU4aN86_emS-_F__jwCGOmN6HzWWKQ',
    appId: '1:337452625695:web:6e2dcec59f03d84ada4a2a',
    messagingSenderId: '337452625695',
    projectId: 'chatter-ai-64d77',
    authDomain: 'chatter-ai-64d77.firebaseapp.com',
    storageBucket: 'chatter-ai-64d77.firebasestorage.app',
    measurementId: 'G-6L1TPPZM2J',
  );
}
